// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaa8fg2lwJ6TvU-6PqvgwAyNG_gpw4Bu0',
    appId: '1:363029739130:web:f2a2dce9223358e500adc3',
    messagingSenderId: '363029739130',
    projectId: 'intellix-b03b0',
    authDomain: 'intellix-b03b0.firebaseapp.com',
    storageBucket: 'intellix-b03b0.firebasestorage.app',
    measurementId: 'G-BTVW0E3250',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwetqn5YGYPkSUpY7kOSVkpgmrUXswylA',
    appId: '1:363029739130:android:fd61c7d87b574e4500adc3',
    messagingSenderId: '363029739130',
    projectId: 'intellix-b03b0',
    storageBucket: 'intellix-b03b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1zHsdsnBne98xl0VltkSzlX0zSKpFiM',
    appId: '1:363029739130:ios:c55307126380cd2500adc3',
    messagingSenderId: '363029739130',
    projectId: 'intellix-b03b0',
    storageBucket: 'intellix-b03b0.firebasestorage.app',
    iosBundleId: 'com.example.intellixClean',
  );

}